language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: 
  - pip install coveralls
  - pip install .
# command to run tests
script: coverage run --source d3r_gcevaluator setup.py test

after_success: coveralls
